
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAR MINUS NUMBER PLUS RPAR TIMESS : EE : E PLUS TE : E MINUS TE : TT : T TIMES FT : T DIVIDE FT : FF : NUMBERE : LPAR E RPARF : MINUS NUMBERE : MINUS LPAR E RPAR'
    
_lr_action_items = {'LPAR':([0,1,7,14,],[1,1,14,1,]),'DIVIDE':([3,4,6,13,16,18,19,20,],[-7,-8,11,-10,11,11,-6,-5,]),'NUMBER':([0,1,7,9,10,11,12,14,17,],[4,4,13,4,4,4,4,4,13,]),'RPAR':([3,4,6,8,13,15,16,18,19,20,21,22,],[-7,-8,-4,15,-10,-9,-2,-3,-6,-5,22,-11,]),'PLUS':([2,3,4,6,8,13,15,16,18,19,20,21,22,],[9,-7,-8,-4,9,-10,-9,-2,-3,-6,-5,9,-11,]),'TIMES':([3,4,6,13,16,18,19,20,],[-7,-8,12,-10,12,12,-6,-5,]),'MINUS':([0,1,2,3,4,6,8,9,10,11,12,13,14,15,16,18,19,20,21,22,],[7,7,10,-7,-8,-4,10,17,17,17,17,-10,7,-9,-2,-3,-6,-5,10,-11,]),'$end':([2,3,4,5,6,13,15,16,18,19,20,22,],[-1,-7,-8,0,-4,-10,-9,-2,-3,-6,-5,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[5,]),'E':([0,1,14,],[2,8,21,]),'T':([0,1,9,10,14,],[6,6,16,18,6,]),'F':([0,1,9,10,11,12,14,],[3,3,3,3,19,20,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> E','S',1,'p_s','Calculator_PLY.py',37),
  ('E -> E PLUS T','E',3,'p_ep','Calculator_PLY.py',41),
  ('E -> E MINUS T','E',3,'p_em','Calculator_PLY.py',45),
  ('E -> T','E',1,'p_et','Calculator_PLY.py',49),
  ('T -> T TIMES F','T',3,'p_tm','Calculator_PLY.py',53),
  ('T -> T DIVIDE F','T',3,'p_td','Calculator_PLY.py',57),
  ('T -> F','T',1,'p_tf','Calculator_PLY.py',61),
  ('F -> NUMBER','F',1,'p_fa','Calculator_PLY.py',65),
  ('E -> LPAR E RPAR','E',3,'p_fp','Calculator_PLY.py',70),
  ('F -> MINUS NUMBER','F',2,'p_fan','Calculator_PLY.py',75),
  ('E -> MINUS LPAR E RPAR','E',4,'p_fpn','Calculator_PLY.py',80),
]
